# Generated by Django 2.1.2 on 2018-11-05 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 18, 10, 3, 684532)),
        ),
    ]
