# Generated by Django 2.1.2 on 2018-11-05 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0003_auto_20181105_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ASP.ClinicManager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatchTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 21, 32, 12, 552178)),
        ),
        migrations.AlterField(
            model_name='order',
            name='placeTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 21, 32, 12, 552178)),
        ),
    ]
