# Generated by Django 2.1.2 on 2018-11-05 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0004_auto_20181105_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatchTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 23, 29, 17, 852874)),
        ),
        migrations.AlterField(
            model_name='order',
            name='placeTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 23, 29, 17, 852874)),
        ),
    ]
