# Generated by Django 2.1.2 on 2018-11-19 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0006_auto_20181106_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='deliveredTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 21, 5, 49, 55783)),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='supply',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatchTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 21, 5, 49, 55783)),
        ),
        migrations.AlterField(
            model_name='order',
            name='placeTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 21, 5, 49, 55783)),
        ),
        migrations.AlterField(
            model_name='supply',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
