# Generated by Django 2.1.2 on 2018-11-19 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0006_auto_20181106_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatchTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 18, 40, 51, 328170)),
        ),
        migrations.AlterField(
            model_name='order',
            name='placeTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 18, 40, 51, 328170)),
        ),
    ]
