# Generated by Django 2.1.2 on 2018-11-19 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0007_auto_20181119_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatchTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 18, 57, 6, 390561)),
        ),
        migrations.AlterField(
            model_name='order',
            name='placeTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 18, 57, 6, 390561)),
        ),
    ]
