# Generated by Django 2.1.2 on 2018-11-19 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0009_auto_20181119_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatchTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 21, 26, 43, 586747)),
        ),
        migrations.AlterField(
            model_name='order',
            name='placeTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 21, 26, 43, 586747)),
        ),
        migrations.AlterField(
            model_name='supply',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
