# Generated by Django 2.1.2 on 2018-11-19 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0011_auto_20181119_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatchTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 22, 7, 59, 45593)),
        ),
        migrations.AlterField(
            model_name='order',
            name='placeTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 22, 7, 59, 45593)),
        ),
        migrations.AlterField(
            model_name='supply',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
